name: dia_router
description: A router for Dia. WARNING do not use it in production! It is alfa version and they need in more work!
version: 0.0.1
homepage: https://github.com/unger1984/dia_router

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dia: ^0.0.3
#    path: ../dia
  path_to_regexp: ^0.4.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
