name: dia_router
description: A router for Dia. Allow add dia middlewares for handle different url addresses.
version: 0.1.5
homepage: https://github.com/unger1984/dia_router

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dia: ^0.1.3
  path_to_regexp: ^0.4.0

dev_dependencies:
  dart_code_metrics: ^3.0.0
  pedantic: ^1.11.0
  test: ^1.16.8
  http: ^0.13.1
